#!/bin/sh
#
# Sync the local debian repository to the remote repo.
# This is effectively a "publish" command.

rsync -r -v --delete ~/deb/repository/ sixarm.com:/var/www/sixarm.com/html/deb/repository/
